# Generated by Django 4.2.30 on 2026-08-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gate_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='ticket_collection_timeframe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
