# Generated by Django 4.2.30 on 2026-06-13 17:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_add_promotion_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='event_type',
            field=models.CharField(blank=True, choices=[('membership_payment', 'membership_payment'), ('ticket_booking', 'ticket_booking'), ('transport_booking', 'transport_booking')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 6, 13, 17, 35, 20, 707566, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
