# Generated by Django 4.2.30 on 2026-06-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Account',
                'verbose_name_plural': 'Points Accounts',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('membership_payment', 'Membership Payment'), ('ticket_booking', 'Ticket Booking'), ('transport_booking', 'Transport Booking'), ('reward_redemption', 'Reward Redemption'), ('manual_adjustment', 'Manual Adjustment')], default='manual_adjustment', max_length=30)),
                ('points', models.IntegerField(help_text='Positive or negative integer')),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='points.pointsaccount')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
