# Generated by Django 4.2.30 on 2026-05-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_change_window_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
