# Generated by Django 4.2.30 on 2026-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='booked', max_length=10),
        ),
    ]
