# Generated by Django 4.2.30 on 2026-08-01 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('VERIFIED', 'Verified'), ('VERIFICATION_EXPIRED', 'Verification Expired'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('VERIFICATION_PENDING', 'Verification Pending'), ('SUPPORTER_SUSPENDED', 'Supporter Suspended'), ('BRANCH_INACTIVE', 'Branch Inactive'), ('MANUAL_OVERRIDE', 'Manual Override'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_eligibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporter Eligibility',
                'verbose_name_plural': 'Supporter Eligibility',
            },
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Verification',
                'verbose_name_plural': 'Student Verifications',
            },
        ),
    ]
