# Generated by Django 4.2.30 on 2026-04-28 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('golden', 'Golden')], default='basic', max_length=10),
        ),
    ]
