# Generated by Django 4.2.30 on 2026-08-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0010_populate_branch_category_institution'),
        ('matches', '0002_match_gate_number_match_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('booked', models.PositiveIntegerField(default=0)),
                ('ticket_ready', models.PositiveIntegerField(default=0)),
                ('collected', models.PositiveIntegerField(default=0)),
                ('attended', models.PositiveIntegerField(default=0)),
                ('verification_completed', models.PositiveIntegerField(default=0)),
                ('transport_booked', models.PositiveIntegerField(default=0)),
                ('transport_capacity', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_snapshots', to='branches.branch')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_snapshots', to='matches.match')),
            ],
            options={
                'ordering': ['-snapshot_date', 'branch__name'],
                'unique_together': {('snapshot_date', 'branch', 'match')},
            },
        ),
    ]
