# Generated by Django 4.2.30 on 2026-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branchrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrole',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('SECRETARY', 'Secretary'), ('BRANCH_ADMIN', 'Branch Admin'), ('JOURNEY_COORDINATOR', 'Journey Coordinator'), ('TRANSPORT_COORDINATOR', 'Transport Coordinator'), ('TICKET_DISTRIBUTOR', 'Ticket Distributor'), ('STUDENT_VERIFIER', 'Student Verifier'), ('COMMUNICATIONS_OFFICER', 'Communications Officer')], max_length=30),
        ),
    ]
