# Generated by Django 4.2.30 on 2026-08-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0005_alter_branchrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branch',
            name='ticket_collection_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branchrole',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('BRANCH_ADMIN', 'Branch Admin')], max_length=30),
        ),
        migrations.CreateModel(
            name='CommitteeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADMIN_PROMOTED', 'Admin Promoted'), ('ADMIN_REMOVED', 'Admin Removed'), ('SUPPORTER_VERIFIED', 'Supporter Verified'), ('TICKET_ALLOCATED', 'Ticket Allocated'), ('TICKET_COLLECTED', 'Ticket Collected'), ('ATTENDANCE_RECORDED', 'Attendance Recorded')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_activities_done', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_activities', to='branches.branch')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_activities_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
