# Generated by Django 4.2.30 on 2026-08-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0006_branch_description_branch_meeting_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('VICE_CHAIRPERSON', 'Vice Chairperson'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('MEDIA_OFFICER', 'Media Officer'), ('LOGISTICS_COORDINATOR', 'Logistics Coordinator')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_positions', to='branches.branch')),
                ('branch_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_position', to='branches.branchrole')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committee_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
