# Generated by ChatGPT - adds operational_match FK to Branch
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_committeeposition'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='operational_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_branches', to='matches.match'),
        ),
    ]
