# Generated by Django 4.2.30 on 2026-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_add_operational_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('INSTITUTIONAL', 'Institutional')], default='COMMUNITY', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
