# Generated by Django 4.2.30 on 2026-08-14 13:25

from django.db import migrations


def populate_branch_category_institution(apps, schema_editor):
    """Populate category and institution for existing branches."""
    Branch = apps.get_model('branches', 'Branch')
    
    # Define institutional branches
    institutional_branches = {
        'Tuks': 'University of Pretoria',
        'Wits': 'University of the Witwatersrand',
    }
    
    # Update institutional branches
    for branch_name, institution_name in institutional_branches.items():
        Branch.objects.filter(name=branch_name).update(
            category='INSTITUTIONAL',
            institution=institution_name
        )
    
    # All other branches default to COMMUNITY
    for branch in Branch.objects.exclude(name__in=institutional_branches.keys()):
        branch.category = 'COMMUNITY'
        branch.institution = ''
        branch.save(update_fields=['category', 'institution'])


def reverse_populate(apps, schema_editor):
    """Reverse the population."""
    Branch = apps.get_model('branches', 'Branch')
    Branch.objects.all().update(category='COMMUNITY', institution='')


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_branch_category_branch_institution'),
    ]

    operations = [
        migrations.RunPython(populate_branch_category_institution, reverse_populate),
    ]
