# Generated by Django 4.2.30 on 2026-08-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('branches', '0004_branchrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='branches.branch')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='matches.match')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'BOOKED'])), fields=('supporter', 'branch', 'match'), name='unique_active_journey_per_supporter_branch_match'),
        ),
    ]
