# Generated by Django 4.2.30 on 2026-08-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_ticket_status'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='collection_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey', to='ticketing.ticket'),
        ),
        migrations.AddField(
            model_name='journey',
            name='ticket_allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('TICKET_READY', 'Ticket Ready'), ('TICKET_COLLECTED', 'Ticket Collected'), ('MATCH_ATTENDED', 'Match Attended')], default='OPEN', max_length=20),
        ),
    ]
