# Generated by Django 4.2.30 on 2026-08-01 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0002_journey_collection_code_journey_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='ticket_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='ticket_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_journeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
