# Generated by Django 4.2.30 on 2026-08-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_journey_attended_at_journey_attended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='collection_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
