# Generated by Django 4.2.30 on 2026-08-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_alter_journey_collection_code'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS unique_active_journey_per_supporter_branch_match
            ON journeys_journey (supporter_id, branch_id, match_id)
            WHERE status IN ('OPEN', 'BOOKED');
            """,
            reverse_sql="DROP INDEX IF EXISTS unique_active_journey_per_supporter_branch_match;",
        ),
    ]
