# Generated by Django 4.2.30 on 2026-06-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_reward_minimum_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardredemption',
            options={'verbose_name': 'Reward Redemption', 'verbose_name_plural': 'Reward Redemptions'},
        ),
    ]
